version: 2

sources:
    -   name: airbnb
        schema: raw
        tables:
            -   name: listings
                identifier: raw_listings
                description: Raw dump of Airbnb listings in Berlin taken from Inside Airbnb site
            -   name: hosts
                identifier: raw_hosts
                description: Raw dump of Airbnb hosts in Berlin taken from Inside Airbnb site
            -   name: reviews
                identifier: raw_reviews
                description: Raw dump of Airbnb reviews in Berlin taken from Inside Airbnb site
                loaded_at_field: date
                freshness:
                    warn_after:
                        count: 1
                        period: hour
                    error_after: 
                        count: 24
                        period: hour